
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ch.ffhs.fac.flang.parser;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int SQUARE_OPEN = 20;
  public static final int STRING_LITERAL = 36;
  public static final int ASTERISK = 27;
  public static final int SLASH = 28;
  public static final int NOT_EQUAL = 30;
  public static final int INTEGER = 37;
  public static final int CURLY_CLOSED = 19;
  public static final int GREATER = 33;
  public static final int LESS = 31;
  public static final int FOR = 7;
  public static final int MINUS = 26;
  public static final int AND = 5;
  public static final int OR = 6;
  public static final int SQUARE_CLOSED = 21;
  public static final int COMMA = 24;
  public static final int LESS_EQUAL = 32;
  public static final int PLUS = 25;
  public static final int ASSIGN = 22;
  public static final int IF = 12;
  public static final int ROUND_OPEN = 16;
  public static final int ROUND_CLOSED = 17;
  public static final int EOF = 0;
  public static final int CURLY_OPEN = 18;
  public static final int RETURN = 15;
  public static final int EQUAL = 29;
  public static final int BY = 10;
  public static final int TRUE = 2;
  public static final int GREATER_EQUAL = 34;
  public static final int error = 1;
  public static final int UNDEFINED = 4;
  public static final int FROM = 8;
  public static final int COLON = 23;
  public static final int ELSE = 13;
  public static final int TO = 9;
  public static final int WHILE = 11;
  public static final int END = 14;
  public static final int FALSE = 3;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "UNDEFINED",
  "AND",
  "OR",
  "FOR",
  "FROM",
  "TO",
  "BY",
  "WHILE",
  "IF",
  "ELSE",
  "END",
  "RETURN",
  "ROUND_OPEN",
  "ROUND_CLOSED",
  "CURLY_OPEN",
  "CURLY_CLOSED",
  "SQUARE_OPEN",
  "SQUARE_CLOSED",
  "ASSIGN",
  "COLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "ASTERISK",
  "SLASH",
  "EQUAL",
  "NOT_EQUAL",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "IDENTIFIER",
  "STRING_LITERAL",
  "INTEGER"
  };
}

